### ISSUE TITLE
Terminating app due to uncaught exception

### ISSUE THREAD

**Issue by sanderwapstra** [firofame/react-native-compass-heading#1]
Hi, thank you for releasing this package! I'm trying to use it but when I start the app it doesn't load. In Xcode it says:

`Terminating app due to uncaught exception 'NSInternalInconsistencyException', reason: 'Error when sending event: HeadingUpdated with body: 323.4593505859375. Bridge is not set. This is probably because you've explicitly synthesized the bridge in CompassHeading, even though it's inherited from RCTEventEmitter.'`

I'm using it in my main `app.js` on `componentDidMount` and without hooks (React Native 0.59.3). Any ideas? Thanks!

**Comment by sam17896** [comment]
@sanderwapstra did you ever solve this ???

**Comment by sanderwapstra** [comment]
@sam17896 No, I ended up using a fork of `react-native-simple-compass` instead (https://github.com/sanderwapstra/react-native-simple-compass)

**Comment by firofame** [comment]
fixed
