### ISSUE TITLE
undefined everywhere

### ISSUE THREAD

**Issue by dozsolti** [firofame/react-native-compass-heading#16]
I followed the installation instructions and I've got undefined for both heading and accuracy, while testing in emulator.
This is the code I am using and the logs says undefined:
`
     import React, { useState, useEffect } from "react"
    import { Image, StyleSheet } from "react-native"
    import CompassHeading from "react-native-compass-heading"
    function Compass() {
                   const [compassHeading, setCompassHeading] = useState(0)

	useEffect(() => {
		const degree_update_rate = 3

		// accuracy on android will be hardcoded to 1
		// since the value is not available.
		// For iOS, it is in degrees
		CompassHeading.start(degree_update_rate, ({ heading, accuracy }) => {
            console.log({heading, accuracy})
			setCompassHeading(heading)
		})

		return () => {
			CompassHeading.stop()
		}
	}, [])
    if(!compassHeading) return null
	return (
		<Image
			style={[
				styles.image,
				{ transform: [{ rotate: `${360 - compassHeading}deg` }] },
			]}
			resizeMode="contain"
			source={require("../compass.png")}
		/>
	)}
    const styles = StyleSheet.create({
	image: {
		width: "90%",
		flex: 1,
		alignSelf: "center",
	},
    })
    export default Compass
`

**Comment by yelnar** [comment]
Did you find how to solve it?

**Comment by dozsolti** [comment]
Unfortunately not. 
Move to [other module](https://www.npmjs.com/package/react-native-simple-compass)

Also be aware that the Android Emulator is not well calibrated, you will have greater success on a real device
