### ISSUE TITLE
Doesn't work on windows&ubuntu

### ISSUE THREAD

**Issue by Sulaiman122** [firofame/react-native-compass-heading#36]
dear developer
I can't do "npx pod-install" on linux
any solution?

**Comment by firofame** [comment]
"npx pod-install" is not required on linux

**Comment by Sulaiman122** [comment]
alright, I will try
thank you

**Comment by Sulaiman122** [comment]
Dear developer
does this package work with Expo?
i'm getting error: null is not an object(evaluating 'CompassHeading.start')

Regards

**Comment by Sulaiman122** [comment]
> "npx pod-install" is not required on linux

Dear developer
does this package work with Expo?
i'm getting error: null is not an object(evaluating 'CompassHeading.start')

Regards
