### ISSUE TITLE
'Corelocation/CoreLocation.h' file not found

### ISSUE THREAD

**Issue by marcoalmeidaelsys** [firofame/react-native-compass-heading#41]
I added the library to my project and it works perfectly on android, but when trying to run it on iOS Simulator through Xcode it shows this error: 'Corelocation/CoreLocation.h' file not found

Has anyone ever experienced this? Did I forget something?

Try in:
iOS 16.2
Xcode 14.2
RN 0.71.0

**Comment by billyu1228** [comment]
seem like the problem is
#import <Corelocation/CoreLocation.h>

should be change to 
#import <CoreLocation/CoreLocation.h>

i change this in xcode, problem gone
